spring:
  mail:
    host: smtp.163.com
    username: 15592991875@163.com
    password: TabloJhin1996163
    default-encoding: utf-8
  redis:
    host: localhost
    password: 236375
    port: 6379
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    timeout: 10000 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8 # 连接池中的最大连接数 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 10
      max-active: 50
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      driver-class-name: com.mysql.cj.jdbc.Driver
      validation-query: SELECT 1 FROM DUAL
      max-wait: 60000
      username: root
      password: root
      time-between-eviction-runs-millis: 60000
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
logging:
  level:
    com.bytedance.postoffice: DEBUG
#  config: classpath:spring-logback.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.aku.attendance.common.model
